<a href="https://colab.research.google.com/github/lucas-estanislau/pe-de-meia/blob/Teste-de-otimiza%C3%A7%C3%A3o-da-coleta/02_agrega%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import numpy as np
from google.colab import drive
import os

In [44]:
# Concatena todos os meses de todos os anos em um único dataframe
anos = [2024, 2025, 2026]
dfs = []
caminho = "/content/drive/MyDrive/pe-de-meia/pe-de-meia-data"

for ano in anos:
    pasta_ano = os.path.join(caminho, str(ano))

    for arquivo in sorted(os.listdir(pasta_ano)):
        if arquivo.endswith(".csv"):
            caminho_arquivo = os.path.join(pasta_ano, arquivo)

            df = pd.read_csv(caminho_arquivo)
            df["ANO"] = ano
            dfs.append(df)

            print(f"{ano} - {arquivo} carregado!")

df_final = pd.concat(dfs, ignore_index=True)

2024 - abr24_uf.csv carregado!
2024 - ago24_uf.csv carregado!
2024 - dez24_uf.csv carregado!
2024 - jun24_uf.csv carregado!
2024 - mai24_uf.csv carregado!
2024 - mar24_uf.csv carregado!
2024 - nov24_uf.csv carregado!
2024 - out24_uf.csv carregado!
2024 - set24_uf.csv carregado!
2025 - abr25_uf.csv carregado!
2025 - ago25_uf.csv carregado!
2025 - dez25_uf.csv carregado!
2025 - fev25_uf.csv carregado!
2025 - jan25_uf.csv carregado!
2025 - jul25_uf.csv carregado!
2025 - jun25_uf.csv carregado!
2025 - mai25_uf.csv carregado!
2025 - mar25_uf.csv carregado!
2025 - nov25_uf.csv carregado!
2025 - out25_uf.csv carregado!
2025 - set25_uf.csv carregado!
2026 - abr26_uf.csv carregado!
2026 - fev26_uf.csv carregado!
2026 - jun26_uf.csv carregado!
2026 - mai26_uf.csv carregado!
2026 - mar26_uf.csv carregado!

In [45]:
df_final

      UF TIPO INCENTIVO  VALOR_TOTAL  QUANTIDADE_PAGAMENTOS   ANO
0     AC     Frequência    3133200.0                  15666  2024
1     AC      Matrícula    1839800.0                   9199  2024
2     AL     Frequência   13613400.0                  68067  2024
3     AL      Matrícula     272000.0                   1360  2024
4     AM     Frequência   17360600.0                  86803  2024
...   ..            ...          ...                    ...   ...
2100  SP      Matrícula   99670200.0                 498351  2026
2101  TO      Conclusão    5095000.0                   5095  2026
2102  TO           Enem     563400.0                   2817  2026
2103  TO     Frequência       9800.0                     49  2026
2104  TO      Matrícula    7264400.0                  36322  2026

[2105 rows x 5 columns]

In [46]:
# Realiza a operação de soma para cada tipo de incentivo para cada UF
df_pdm_anual = (
    df_final
    .groupby(
        ["ANO", "UF", "TIPO INCENTIVO"],
        as_index=False
    )
    .agg(
        VALOR_TOTAL=("VALOR_TOTAL", "sum"),
        QUANTIDADE_PAGAMENTOS=("QUANTIDADE_PAGAMENTOS", "sum")
    )
)

df_pdm_anual = df_pdm_anual.sort_values(
    ["ANO", "UF", "TIPO INCENTIVO"]
).reset_index(drop=True)

display(df_pdm_anual.head())

    ANO  UF TIPO INCENTIVO  VALOR_TOTAL  QUANTIDADE_PAGAMENTOS
0  2024  AC     Frequência   33242625.0                 165877
1  2024  AC      Matrícula    5205400.0                  26027
2  2024  AL     Frequência  126806125.0                 631927
3  2024  AL      Matrícula   19438600.0                  97193
4  2024  AM     Frequência  128097525.0                 639118

In [47]:
df_pdm_anual

      ANO  UF TIPO INCENTIVO  VALOR_TOTAL  QUANTIDADE_PAGAMENTOS
0    2024  AC     Frequência   33242625.0                 165877
1    2024  AC      Matrícula    5205400.0                  26027
2    2024  AL     Frequência  126806125.0                 631927
3    2024  AL      Matrícula   19438600.0                  97193
4    2024  AM     Frequência  128097525.0                 639118
..    ...  ..            ...          ...                    ...
265  2026  SP      Matrícula  106481200.0                 532406
266  2026  TO      Conclusão   32088000.0                  38544
267  2026  TO           Enem     974200.0                   4871
268  2026  TO     Frequência   22019475.0                 109859
269  2026  TO      Matrícula    7861200.0                  39306

[270 rows x 5 columns]

In [48]:
# Salva o dataframe com todos os anos, meses, UFs e tipo de incentivo
df_pdm_anual.to_csv(
            f"/content/drive/MyDrive/pe-de-meia/agregados/pe-de-meia-2024-2026.csv",
            index=False
        )

In [49]:
# Agrupa o valor total de pagamentos por ano em cada UF, independente do tipo de incentivo
df_valor_total = df_pdm_anual.groupby(["ANO", "UF"], as_index=False).agg(
        VALOR_TOTAL=("VALOR_TOTAL", "sum"),
        QUANTIDADE_PAGAMENTOS=("QUANTIDADE_PAGAMENTOS", "sum")
    )

In [50]:
df_valor_total

     ANO  UF  VALOR_TOTAL  QUANTIDADE_PAGAMENTOS
0   2024  AC   38448025.0                 191904
1   2024  AL  146244725.0                 729120
2   2024  AM  155529925.0                 776280
3   2024  AP   36293675.0                 181301
4   2024  BA  605883725.0                3018872
..   ...  ..          ...                    ...
76  2026  RS  171764575.0                 512329
77  2026  SC   85720950.0                 265445
78  2026  SE  103432000.0                 301014
79  2026  SP  782836450.0                2160228
80  2026  TO   62942875.0                 192580

[81 rows x 4 columns]

In [51]:
# Verificando se há 27 estados para cada ano para evitar dado perdido
df_valor_total.groupby("ANO").size()

ANO
2024    27
2025    27
2026    27
dtype: int64

In [52]:
# Salva o dataframe agrupado por ano com valor total para cada UF
df_valor_total.to_csv(
            f"/content/drive/MyDrive/pe-de-meia/agregados/pe-de-meia-2024-2026-total-UF.csv",
            index=False
        )

## Dados INEP

In [53]:
caminho = "/content/drive/MyDrive/pe-de-meia/inep/inep-data/taxas_em_uf_2007_2025.csv"

df_inep = pd.read_csv(caminho)

## Juntando os dados do Pé-De-Meia com os do as taxas de rendimento do INEP

In [54]:
df_final = pd.merge(
    df_valor_total,
    df_inep,
    on=["ANO", "UF"],
    how="left",
    validate="one_to_one",
    indicator=True
)

display(df_final.head())

,ANO,UF,VALOR_TOTAL,QUANTIDADE_PAGAMENTOS,TAXA_APROVACAO,TAXA_REPROVACAO,TAXA_ABANDONO,_merge
0,2024,AC,38448025.0,191904,87.4,7.8,4.8,both
1,2024,AL,146244725.0,729120,91.0,5.3,3.7,both
2,2024,AM,155529925.0,776280,89.7,6.3,4.0,both
3,2024,AP,36293675.0,181301,89.0,7.5,3.5,both
4,2024,BA,605883725.0,3018872,89.3,4.9,5.8,both

In [55]:
df_final

,ANO,UF,VALOR_TOTAL,QUANTIDADE_PAGAMENTOS,TAXA_APROVACAO,TAXA_REPROVACAO,TAXA_ABANDONO,_merge
0,2024,AC,38448025.0,191904,87.4,7.8,4.8,both
1,2024,AL,146244725.0,729120,91.0,5.3,3.7,both
2,2024,AM,155529925.0,776280,89.7,6.3,4.0,both
3,2024,AP,36293675.0,181301,89.0,7.5,3.5,both
4,2024,BA,605883725.0,3018872,89.3,4.9,5.8,both
...,...,...,...,...,...,...,...,...
76,2026,RS,171764575.0,512329,NaN,NaN,NaN,left_only
77,2026,SC,85720950.0,265445,NaN,NaN,NaN,left_only
78,2026,SE,103432000.0,301014,NaN,NaN,NaN,left_only
79,2026,SP,782836450.0,2160228,NaN,NaN,NaN,left_only
80,2026,TO,62942875.0,192580,NaN,NaN,NaN,left_only

In [56]:
df_final.groupby(["ANO", "_merge"], observed=True).size()

ANO   _merge
2024  both         27
2025  both         27
2026  left_only    27
dtype: int64

In [57]:
df_final[df_final["ANO"].isin([2024, 2025])]["_merge"].value_counts()

_merge
both          54
left_only      0
right_only     0
Name: count, dtype: int64

Como no momento da realização desta analise ainda não há dados de taxas de rendimento para o ano de 2026, a coluna "_merge" para o ano de 2026 contém "left_only", pois só há dados do pé-de-meia.

In [58]:
# Dataframe para analisar somente os anos de 2024 e 2025
df_analise = (
    df_final[df_final["_merge"] == "both"]
    .drop(columns="_merge")
    .copy()
)

In [59]:
# Salva o dataframe com a junção dos dados do Pé-de-Meia e taxas de rendimento de 2024 e 2025
df_analise.to_csv(
            f"/content/drive/MyDrive/pe-de-meia/agregados/pdm-tx-rendimento-2024-2025.csv",
            index=False
        )